# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b41048116cfb28681a47f0c246f305d76227f6416b705bff4a29b17d57a900348f22142c594ce67a642b756b33e8d5a7ef6dcb0465bc1812b4337c19162486bb

test:
  secret_key_base: f736173d5ed3708c3c535343069c83c352c6fd1cbe76e09c71207f0b468082068078c2afd5b169ed996f79fc991a25e5f95a96643b09cdb4de4040f72ed7472c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
